Update cyclic.py
a cyclic -l was broken with python 3 with the following error:
$ cyclic -l eaac
[!] Pwntools does not support 32-bit Python.  Use a 64-bit release.
Traceback (most recent call last):
  File "/usr/local/bin/cyclic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pwnlib/commandline/common.py", line 32, in main
    pwnlib.commandline.main.main()
  File "/usr/local/lib/python3.8/dist-packages/pwnlib/commandline/main.py", line 54, in main
    commands[args.command](args)
  File "/usr/local/lib/python3.8/dist-packages/pwnlib/commandline/cyclic.py", line 76, in main
    if not all(c in alphabet for c in pat):
  File "/usr/local/lib/python3.8/dist-packages/pwnlib/commandline/cyclic.py", line 76, in <genexpr>
    if not all(c in alphabet for c in pat):
TypeError: a bytes-like object is required, not 'str'